const STORAGE_KEY = 'gundam-favorites';
const MIGRATION_KEY = 'gundam-favorites-v2-migrated';

function readFavorites(): string[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as string[];
  } catch {
    return [];
  }
}

function writeFavorites(ids: string[]): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(ids));
  } catch {
    // localStorage unavailable – ignore
  }
}

export function getFavorites(): string[] {
  return readFavorites();
}

export function addFavorite(modelId: string): void {
  const ids = readFavorites();
  if (!ids.includes(modelId)) {
    writeFavorites([...ids, modelId]);
  }
}

export function removeFavorite(modelId: string): void {
  const ids = readFavorites();
  writeFavorites(ids.filter((id) => id !== modelId));
}

export function isFavorite(modelId: string): boolean {
  return readFavorites().includes(modelId);
}

export function toggleFavorite(modelId: string): boolean {
  if (isFavorite(modelId)) {
    removeFavorite(modelId);
    return false;
  } else {
    addFavorite(modelId);
    return true;
  }
}

/**
 * One-time migration: maps old sequential IDs (e.g. "rg-001") to new IDs
 * that separate regular ("rg-001") and limited ("rg-l-001") numbering.
 *
 * The mapping is read from /data/id-migration.json, which is generated by
 * scripts/src/fix-limited.ts during the data build step.
 */
export async function migrateFavoritesIfNeeded(): Promise<void> {
  try {
    if (localStorage.getItem(MIGRATION_KEY)) return;

    const oldIds = readFavorites();
    if (oldIds.length === 0) {
      localStorage.setItem(MIGRATION_KEY, '1');
      return;
    }

    // Fetch migration map generated by fix-limited.ts
    const res = await fetch('/data/id-migration.json');
    if (!res.ok) {
      // No migration map available -- mark as done to avoid retrying
      localStorage.setItem(MIGRATION_KEY, '1');
      return;
    }
    const migrationMap = (await res.json()) as Record<string, string>;

    const newIds: string[] = [];
    for (const oldId of oldIds) {
      const newId = migrationMap[oldId];
      if (newId) {
        newIds.push(newId);
      } else {
        // Keep old ID if no mapping exists (might still be valid)
        newIds.push(oldId);
      }
    }

    writeFavorites(newIds);
    localStorage.setItem(MIGRATION_KEY, '1');
  } catch {
    // Migration failed -- mark as done to avoid infinite retries
    localStorage.setItem(MIGRATION_KEY, '1');
  }
}
